### ISSUE TITLE
error testing - make sure return jsons properly

### ISSUE THREAD

**Issue by ita-c** [banyancomputer/Rust-Chainlink-EA-API#2]

**Comment by jonahkaye** [comment]
API TESTING TO DO: 
1. multiple proofs
2. reasonably correct other values
3. proofs window num to block number thing implemented sort of 
4. add proofs to data structure
5. add view function to contract for the proofs
6. A mix of good and bad proofs

**Comment by ita-c** [comment]
I'm going to create individual issues for these
